/* TP-LINK EC220_G5 V2 */

#define BOARD_PID		"TL_EC220_G5-V2"
#define BOARD_NAME		"TL_EC220_G5-V2"
#define BOARD_DESC		"TP-Link Archer C5 Wireless Router"
#define BOARD_VENDOR_NAME	"TP-LINK Technologies CO., LTD."
#define BOARD_VENDOR_URL	"http://www.tp-link.com/ru"
#define BOARD_MODEL_URL		"http://www.tp-link.com/ru/support/download/ec220-g5/"
#define BOARD_BOOT_TIME		25
#define BOARD_FLASH_TIME	120
#define BOARD_GPIO_BTN_RESET	13
#define BOARD_GPIO_BTN_WPS	43
#undef  BOARD_GPIO_LED_ALL
#undef  BOARD_GPIO_LED_WIFI
#define BOARD_GPIO_LED_SW2G	2
#define BOARD_GPIO_LED_SW5G	9
#undef  BOARD_GPIO_LED_POWER	42
#define BOARD_GPIO_LED_LAN	1
#define BOARD_GPIO_LED_WAN	53
#undef  BOARD_GPIO_LED_WAN_INVERTED
#undef  BOARD_GPIO_LED_WAN_PHY
#undef  BOARD_GPIO_LED_WAN_PHY_INVERTED
#undef  BOARD_GPIO_LED_USB
#undef  BOARD_GPIO_LED_ROUTER
#undef  BOARD_GPIO_PWR_USB_ON
#undef  BOARD_GPIO_PWR_USB
#undef  BOARD_GPIO_PWR_USB2
#define BOARD_HAS_5G_11AC	1
#define BOARD_NUM_ANT_5G_TX	2
#define BOARD_NUM_ANT_5G_RX	2
#define BOARD_NUM_ANT_2G_TX	2
#define BOARD_NUM_ANT_2G_RX	2
#define BOARD_NUM_ETH_LEDS	0
#define BOARD_NUM_ETH_EPHY	4
#define BOARD_HAS_EPHY_L1000	1
#define BOARD_HAS_EPHY_W1000	1
