/* Dlink DIR-620A1 */
#define BOARD_PID		"RT-N13UB1"
#define BOARD_NAME		"RT-N13U_B1"
#define BOARD_DESC		"ASUS RT-N13U B1 Wireless Router"
#define BOARD_VENDOR_NAME	"ASUSTek Computer Inc."
#define BOARD_VENDOR_URL	"http://www.asus.com/"
#define BOARD_MODEL_URL		"http://www.asus.com/Networking/RTN13U_B1/"
#define BOARD_BOOT_TIME		30
#define BOARD_FLASH_TIME	180
#define BOARD_GPIO_BTN_RESET	10
#define BOARD_GPIO_BTN_WPS	0
#undef  BOARD_GPIO_BTN_WLTOG
#undef  BOARD_GPIO_LED_ALL
#undef BOARD_GPIO_LED_WIFI
#define BOARD_GPIO_LED_POWER	7
#undef BOARD_GPIO_LED_WAN	14
#undef BOARD_GPIO_LED_LAN
#undef BOARD_GPIO_LED_USB
#define BOARD_HAS_5G_11AC	0
#define BOARD_5G_IN_SOC		0
#define BOARD_2G_IN_SOC		1
#define BOARD_NUM_ANT_5G_TX	0
#define BOARD_NUM_ANT_5G_RX	0
#define BOARD_NUM_ANT_2G_TX	2
#define BOARD_NUM_ANT_2G_RX	2
#define BOARD_NUM_ETH_LEDS	0
#define BOARD_HAS_EPHY_L1000	0
#define BOARD_HAS_EPHY_W1000	0
