/* DLink DIR-882*/

#define BOARD_PID		"DIR-882"
#define BOARD_NAME		"DIR-882"
#define BOARD_DESC		"DLink board"
#define BOARD_VENDOR_NAME	"D-Link"
#define BOARD_VENDOR_URL	"http://dlink.com/"
#define BOARD_MODEL_URL		"http://www.dlink.com.cn/"
#define BOARD_BOOT_TIME		30
#define BOARD_FLASH_TIME	120
#define BOARD_GPIO_BTN_RESET	15
#define BOARD_GPIO_BTN_WPS	18
#define BOARD_GPIO_BTN_FN1	7
#undef  BOARD_GPIO_LED_ALL
#undef  BOARD_GPIO_LED_WIFI
#undef  BOARD_GPIO_LED_SW2G
#undef  BOARD_GPIO_LED_SW5G
#define BOARD_GPIO_LED_POWER	16
#undef  BOARD_GPIO_LED_LAN
#define BOARD_GPIO_LED_WAN	3
#define BOARD_GPIO_LED_WAN_PHY	4
#define BOARD_GPIO_LED_USB	13
#define BOARD_GPIO_LED_USB2	14
#undef  BOARD_GPIO_LED_ROUTER
#undef  BOARD_GPIO_PWR_USB
#define BOARD_HAS_5G_11AC	1
#define BOARD_NUM_ANT_5G_TX	4
#define BOARD_NUM_ANT_5G_RX	4
#define BOARD_NUM_ANT_2G_TX	4
#define BOARD_NUM_ANT_2G_RX	4
#define BOARD_NUM_ETH_LEDS	0
#define BOARD_NUM_ETH_EPHY	5
#define BOARD_HAS_EPHY_L1000	1
#define BOARD_HAS_EPHY_W1000	1
#define BOARD_NUM_UPHY_USB3	1
#define BOARD_USB_PORT_SWAP	1
