/* A5-V11_16M*/

#define BOARD_PID		"A5-V11_16M"
#define BOARD_NAME		"A5-V11_16M"
#define BOARD_DESC		"A5-V11_16M Wireless Router"
#define BOARD_VENDOR_NAME	"A5-V11_16M"
#define BOARD_VENDOR_URL	"noname"
#define BOARD_MODEL_URL		"noname"
#define BOARD_BOOT_TIME		20
#define BOARD_FLASH_TIME	120
#define BOARD_GPIO_BTN_RESET	0
#undef  BOARD_GPIO_BTN_WPS	
#undef  BOARD_GPIO_BTN_WLTOG
#undef  BOARD_GPIO_LED_ALL
#undef BOARD_GPIO_LED_WIFI
#undef BOARD_GPIO_LED_POWER	
#undef BOARD_GPIO_LED_WAN
#undef BOARD_GPIO_LED_LAN
#undef  BOARD_GPIO_LED_USB	
#undef  BOARD_GPIO_LED_WPS	
#define BOARD_HAS_5G_11AC	0
#define BOARD_5G_IN_SOC		0
#define BOARD_2G_IN_SOC		1
#define BOARD_NUM_ANT_5G_TX	0
#define BOARD_NUM_ANT_5G_RX	0
#define BOARD_NUM_ANT_2G_TX	1
#define BOARD_NUM_ANT_2G_RX	1
#define BOARD_NUM_ETH_LEDS	0
#define BOARD_HAS_EPHY_L1000	0
#define BOARD_HAS_EPHY_W1000	0
